### ISSUE TITLE
You didn't bump the version in `akamai.go` file.

### ISSUE THREAD

**Issue by alexframe** [akamai/cli#10]
You didn't bump the version in the [`akamai.go`](https://github.com/akamai/cli/blob/f39874a02ce9c253c690bf06f3e608fa064d5047/akamai.go#L50) file - so running the following in 0.1.**1** results in outputting 0.1.**0**

```bash
$ akamai --version
akamai version 0.1.0 # <-- should be 0.1.1
```

**Comment by dshafik** [comment]
@alexframe Good catch; seeing as this would require 0.1.2 for a fix, I've opted to instead automate the detection of this issue moving forward by adding a little more logic to the build script.

Thanks for reporting the issue!
