### ISSUE TITLE
CLI still thinks it is not installed in PATH, but it is

### ISSUE THREAD

**Issue by krzyk** [akamai/cli#106]
I run the cli in command line, installed it in one of my PATH directories.
I run it second time and it still insists that `Akamai CLI is not installed in your PATH`.

I'm running it on Linux and have > 10 elements in path, and installed it into my $HOME/bin directory.

Doing which `akamai` shows it correctly same as running it with `akamai`.

I'm using latest available release.

**Comment by lkowalsk-akamai-com** [comment]
Hi @krzyk, can you please let us know if this is still and issue for you with latest version?
