### ISSUE TITLE
Additional steps required for binary download & install

### ISSUE THREAD

**Issue by nmckay77** [akamai/cli#117]
The download & install section at the bottom of the page at https://developer.akamai.com/cli should have instructions to save file and make it executable. Download on Mac pops-up a window asking what application to use to open the file which is confusing. 

<img width="571" alt="screenshot" src="https://user-images.githubusercontent.com/3465958/105136264-367a7c80-5aa6-11eb-8e32-5341f326d5f8.png">

**Comment by tpw1314** [comment]
Hi @nmckay77 , instruction is given on <Code> home page of this repo.
Kindly perform these commands on Terminal to make it executable.
```
$ chmod +x ~/Downloads/akamai-<VERSION>-<PLATFORM>
$ mv ~/Downloads/akamai-<VERSION>-<PLATFORM> /usr/local/bin/akamai
```

If second step prompts error saying permission denied, kindly add sudo at the front :
`$ sudo mv ~/Downloads/akamai-<VERSION>-<PLATFORM> /usr/local/bin/akamai`
