### ISSUE TITLE
unable to install akamai sandbox

### ISSUE THREAD

**Issue by Hoshiyar0703** [akamai/cli#119]
unable to install the sandbox client:
looking at logs the calls to domain https://repos.akamai.com:443/api/npm/npmjs-
are failing as domain doesn't resolve in dns.

error:
 AKAMAI_LOG=debug akamai install sandbox
Attempting to fetch command from https://github.com/akamai/cli-sandbox.git...
Attempting to fetch command from https://github.com/akamai/cli-sandbox.git...... [OK]

Installing...
INFO[0000] package.json found, running npm package manager
DEBUG[0002] Unable execute package manager (/usr/local/bin/npm install):
DEBUG[0002] npm ERR! code ENOTFOUND
DEBUG[0002] npm ERR! syscall getaddrinfo
DEBUG[0002] npm ERR! errno ENOTFOUND
DEBUG[0002] npm ERR! network request to https://repos.akamai.com:443/api/npm/npmjs-repos/xtend/-/xtend-4.0.1.tgz failed, reason: getaddrinfo ENOTFOUND repos.akamai.com
DEBUG[0002] npm ERR! network This is a problem related to network connectivity.
DEBUG[0002] npm ERR! network In most cases you are behind a proxy or have bad network settings.
DEBUG[0002] npm ERR! network
DEBUG[0002] npm ERR! network If you are behind a proxy, please make sure that the
DEBUG[0002] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
DEBUG[0002]
DEBUG[0002] npm ERR! A complete log of this run can be found in:
DEBUG[0002] npm ERR!     /Users/Hoshiyar.Digari/.npm/_logs/2021-02-05T23_13_42_930Z-debug.log
Installing...... [WARN]

Unable to execute package manager (npm).[
[2021-02-05T23_13_42_930Z-debug.log](https://github.com/akamai/cli/files/5935793/2021-02-05T23_13_42_930Z-debug.log)
](url)

**Comment by robertolopezlopez** [comment]
this does not seem an akamai cli general issue, but more specific to akamai cli sandbox https://github.com/akamai/cli-sandbox/issues/70

**Comment by lkowalsk-akamai-com** [comment]
This is being tracked under cli-sandbox - https://github.com/akamai/cli-sandbox/issues/70
