### ISSUE TITLE
Unable to remove

### ISSUE THREAD

**Issue by mm25151** [akamai/cli#125]
For Akamai CLI 1.2.1, when running in Powershell 5.1 on Windows 10, getting error
Unable to remove old executable: remove .c:\tools\common\akamai.exe.old: The filename, directory name, or volume label syntax is incorrect.

**Comment by robertolopezlopez** [comment]
Hi @mm25151 ,

We are sorry to see that you are having trouble with the manual upgrade. We will release a fix as soon as possible. In the meanwhile and just as a temporary workaround, please try the normal windows command prompt instead of powershell.

Could you please try and let us know? Thanks :-)

**Comment by mm25151** [comment]
Yes, normal windows command prompt does work correctly.
But, I have a number of powershell scripts written around Akamai CLI.
For now, I am able to use version 1.2.0.

From: Roberto López López ***@***.***>
Sent: Thursday, April 29, 2021 8:35 AM
To: akamai/cli ***@***.***>
Cc: Steidler, David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [akamai/cli] Unable to remove (#125)


Hi @mm25151<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mm25151&d=DwMCaQ&c=BX7Y4KpGhcDnIsrgHKqkbfoiiDvjhxwuYUpcrPD7xrE&r=ZACvHxFppB37bccknyyIAWf22AxPeu85OGvYY9JlTT0&m=ksOoB6hGdmGHfLvXImZyPtR16CeTqFNXmeuv_5GVrzk&s=WQlMgdqbFuVadxcSNWY089nXjpmW6QG0H78F7upTx-c&e=> ,

We are sorry to see that you are having trouble with the manual upgrade. We will release a fix as soon as possible. In the meanwhile and just as a temporary workaround, please try the normal windows command prompt instead of powershell.

Could you please try and let us know? Thanks :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_akamai_cli_issues_125-23issuecomment-2D829200949&d=DwMCaQ&c=BX7Y4KpGhcDnIsrgHKqkbfoiiDvjhxwuYUpcrPD7xrE&r=ZACvHxFppB37bccknyyIAWf22AxPeu85OGvYY9JlTT0&m=ksOoB6hGdmGHfLvXImZyPtR16CeTqFNXmeuv_5GVrzk&s=4IW6DdkhnBv9MkkOlWNQzJ1xUBodiAmRpvQ0kvOgNR8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQQYNIPRK3Q7HN44WCLXFITTLFG7RANCNFSM43ZWZ2GQ&d=DwMCaQ&c=BX7Y4KpGhcDnIsrgHKqkbfoiiDvjhxwuYUpcrPD7xrE&r=ZACvHxFppB37bccknyyIAWf22AxPeu85OGvYY9JlTT0&m=ksOoB6hGdmGHfLvXImZyPtR16CeTqFNXmeuv_5GVrzk&s=ijgQbMM0ykcxTTo0x4vE7k6cT156RIRu-RRnV9UXSEQ&e=>.

This e-mail transmission may contain information that is proprietary, privileged and/or confidential and is intended exclusively for the person(s) to whom it is addressed. Any use, copying, retention or disclosure by any person other than the intended recipient or the intended recipient's designees is strictly prohibited. If you are not the intended recipient or their designee, please notify the sender immediately by return e-mail and delete all copies

**Comment by robertolopezlopez** [comment]
Thank you for your answer @mm25151, I am already working on a patch to fix this issue

**Comment by stfsy** [comment]
@robertolopezlopez any updates? ran into this too using git bash on windows

**Comment by stfsy** [comment]
@robertolopezlopez wouldn't #130 fix this problem?

**Comment by lkowalsk-akamai-com** [comment]
Hi @stfsy 
We do have a fix already and we are preparing a new release. It should be availabe soon. We will update this ticket once release is done.

**Comment by lkowalsk-akamai-com** [comment]
We believe that this issue is fixed with 1.3.0 release. Please feel free to reaopen the ticket if thats not the case.
