### ISSUE TITLE
Inconsistent accountSwitchKey parameter

### ISSUE THREAD

**Issue by anirudhbagri** [akamai/cli#126]
`akamai sandbox` and `akamai property` understand different key for accountSwitchKey parameter.

`akamai sandbox` expects `--accountkey` whereas `akamai property` expects `--account-key` param.

**Comment by robertolopezlopez** [comment]
@anirudhbagri : you should address proper teams for that, as of today we do not have control over those repositories so there is little we can do. Please create an issue in either https://github.com/akamai/cli-sandbox or https://github.com/akamai/cli-property for that.

Regards,

Roberto
