### ISSUE TITLE
Docker image looks not working well with Apple M1

### ISSUE THREAD

**Issue by ds1dbx** [akamai/cli#128]
Hi team.

Due to `brew` not working well (same symptom as below issue), I'm trying to use docker image to use Akamai CLI.
Installation itself had no problem, but `akamai/shell` reported me that platform problem. 

```
% docker run -it -v $HOME/.edgerc:/root/.edgerc:ro akamai/shell
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

I believe that issue is causing coming up error while I tried to execute CLI with another error message.

```
Akamai DevOps [~] >> akamai
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

Can I get some help on this?

**Comment by ds1dbx** [comment]
I found closed issue from Akamai docker repository.
https://github.com/akamai/akamai-docker/pull/55

I've manually build docker image from akamai-docker respository then error message went away.
It would be better to replace image of docker hub not to make confusion. :-(

Hope this to be helpful to someone who experiences same issue.

```
% docker run -it -v $HOME/.edgerc:/root/.edgerc:ro akamai/shell
                ___    __                         _
               /   |  / /______ _____ ___  ____ _(_)
              / /| | / //_/ __ `/ __ `__ \/ __ `/ /
             / ___ |/ ,< / /_/ / / / / / / /_/ / /
            /_/  |_/_/|_|\__,_/_/ /_/ /_/\__,_/_/
===============================================================
=  Welcome to the Akamai Docker Image                         =
===============================================================
=  Project page:                                              =
=  https://github.com/akamai/akamai-docker                    =
===============================================================
Akamai DevOps [~] >>
```

**Comment by robertolopezlopez** [comment]
Hi @ds1dbx ,

Thank you for opening this gh issue (and sharing a workaround).

As previously mentioned [in another thread](https://github.com/akamai/cli/issues/127#issuecomment-865703279), unfortunately we are not yet providing any binary for Apple M1 processors. The workarounds at this moment may be either to build the binary by your own or build a new docker image as you suggest. Thus, as there is another thread regarding this issue, I will close this one.

Kind regards,

Roberto

**Comment by avivais** [comment]
@ds1dbx can you share details on how you manually built the docker image as a workaround?
