### ISSUE TITLE
Updating and installing packages does not work with Linux 'yes' command.

### ISSUE THREAD

**Issue by coder755** [akamai/cli#136]
Hello,

I am attempting to utilize the Akamai cli in a Jenkins pipeline. All of our installs are done via automation and command line (aka a cattle vs pet mentality). I would like to use something like the following commands in our Jenkinsfile to install the cli and purge tool:

        sh "curl -v -o akamai -L \"https://github.com/akamai/cli/releases/download/1.3.1/akamai-1.3.1-linux386\""
        sh "chmod +x akamai"
        sh "yes n | ./akamai update"
        sh "yes | ./akamai install purge"

However, I am finding that Akamai cli is not compatible with the 'yes' command. I wonder if I am missing a detail that would make this significantly simpler. Perhaps a flag to force a 'yes'/'no' response. Any suggestions?

**Comment by conpnair** [comment]
This is an issue we are facing in our Github Actions CI/CD as well. Is there an ETA on when the release would be available with this fix?

**Comment by consbish** [comment]
I had the similar issue. Somehow I managed this issue with below command.
akamai install --force purge

Hope this will help if someone is running it through Jenkins or any other CI/CD pipeline.

**Comment by coder755** [comment]
> I had the similar issue. Somehow I managed this issue with below command. akamai install --force purge
> 
> Hope this will help if someone is running it through Jenkins or any other CI/CD pipeline.

Hey @consbish. Unfortunately this doesn't resolve the issue of installing and updating the CLI. Thanks for trying to help out.

**Comment by coder755** [comment]
As a side note. I did find a work around. To restate the problem space: after downloading the installation, manual inputs are required (these are incompatible with the linux yes command).
However, after doing the install manually, I found a configuration file (.akamai-cli/config) that contained flags being set by the inputs. So I copied that file and placed it in the Jenkins config file storage area. The implementation then became writing the configuration to the file and location the akamai install was expecting. Then TADA! No inputs required :D

#wonthegame

**Comment by robertolopezlopez** [comment]
Hi @coder755 and @conpnair ,

This  should be fixed in the new 1.4.2 release which we have done today. Thus I will close this issue now. If you happen to have problems again, please reopen it :-)

Regards,

Roberto
