### ISSUE TITLE
Warning for insecure or plugins

### ISSUE THREAD

**Issue by ericdebeij** [akamai/cli#137]
The CLI is provided by Akamai, Akamai is a security company and customers can reasonably assume that plugins delivered from the default repository are maintained.

There are however CLI's in the akamai repository that are in development or even at the end of their life-cycle. Look for example to the CLI for NetStorage which hasn't been updated in 4 years and is still in preview mode.

In my opinion you should only be able to install an in-development or out-dated CLI if you give an explicit concent, either by selecting a different repository or by adding a flag that confirms that you are aware that the CLI is not maintained by Akamai.

**Comment by argenstijn** [comment]
Agreed. Also Netstorage CLI is promoted on the website of Akamai. Customer assume then that the plugin is secure and also maintained.

For one all communication between netstorage CLI and akamai is done over HTTP!.

**Comment by ericdebeij** [comment]
Issue is being tracked as part of the review process of the developer experience team. Work is in progress.
The existing CLI packages, for specific applications, have been written by several teams at Akamai over time. The Developer Experience team is triaging items that need attention and determining how to get issues resolved, with application teams’ support. Some of the older CLI packages have been removed recently, and the remaining CLIs are being reviewed for issues as well as opportunities to be re-written, consolidated, or EOLed.
