### ISSUE TITLE
Outdated URL in GitHub repo

### ISSUE THREAD

**Issue by AustinGil** [akamai/cli#139]
Hello, I just noticed the URL for this GitHub repo is pointing to a page that no longer exists.

Can I recommend replacing it with one of these:
https://developer.akamai.com/getting-started/cli
https://techdocs.akamai.com/developer/docs/about-clis

**Comment by lkowalsk-akamai-com** [comment]
Hi @AustinGil 
Thanks for pointing this out. I've updated the URL with https://techdocs.akamai.com/developer/docs/about-clis 
I'm closing the ticket, feel free to reopen in case it would be needed.
