### ISSUE TITLE
Readme incorrectly uses `akamai install`

### ISSUE THREAD

**Issue by tsal** [akamai/cli#14]
The cli currently uses `akamai get` to install packages, but the README says `akamai install`.  Seems like a minor issue, but I can see it being a frustration point for new users.

**Comment by kporowski** [comment]
`akamai get` changed to `akamai install` in version 0.2.0

**Comment by dshafik** [comment]
@tsal @kporowski is correct about the change in 0.2.0. I will also be releasing 0.3.0 today and updating homebrew (which is currently still on 0.1.1) if that is what you are using to install it.

Thanks!

**Comment by tsal** [comment]
@dshafik - sorry for the delayed response, but yes! I _am_ using homebrew.  Thanks!
