### ISSUE TITLE
All plugins should fallback to default if that specific section doesn't exist

### ISSUE THREAD

**Issue by jcheshire** [akamai/cli#145]
Why don't all fallback to default if that specific section doesn't exist?
Or fix so everything uses [default]

Having to duplicate in the .edgerc or type --section default is a bit of annoying.

_Originally posted by @cdenneen in https://github.com/akamai/cli/issues/32#issuecomment-595476744_

**Comment by lkowalsk-akamai-com** [comment]
Thank you for rising this issue. We will discuss internally and consider to apply suggested change.

**Comment by robertolopezlopez** [comment]
CLI itself does not make use of any `.edgerc` credentials. Instead, this is handled by the `cli-*` packages. Please, create this issue in the desired package repository.

Regards,

Roberto
