### ISSUE TITLE
Privacy update not working

### ISSUE THREAD

**Issue by per-garden** [akamai/cli#147]
When using akamai-cli in one of our projects we try to automate handling. Setting endpoint resources to public/private, does not seems to work though.

Supposedly one should be able to write something like "akamai api-gateway  privacy-add --endpoint=764997 --version=30 -public --resource /performance". That would be to make the resource "/performance" public. Nor that, nor any tweaked calls (e.g. using JSON) ever result in anything but "json: cannot unmarshal object into Go struct field APIPrivacyResource.methods of type []string" though. What is wrong? I'm using akamai-cli 1.4.1.

As the akamai-cli is a statically linked binary (so everything should be included, right?), I assume this is some internal problem in akamai-cli.

**Comment by robertolopezlopez** [comment]
hi @per-garden ,

Please try executing the same command directly with the cli-api-gateway binary. Are you getting the same error?

https://github.com/akamai/cli-api-gateway/releases/latest

Regards,

Roberto

**Comment by per-garden** [comment]
Where is the download link?

**Comment by per-garden** [comment]
Is there a precompiled binary?

per@lex14:~/junk/cli-api-gateway-0.1.0$ dep ensure
bash: dep: command not found
per@lex14:~/junk/cli-api-gateway-0.1.0$

**Comment by per-garden** [comment]
Go programming is new is new territory to me. Still, downloaded and built latest as recommended. Same problem though:

`per@lex14:~/projects/smaaland/backend$ echo $GOROOT
/usr/local/go
per@lex14:~/projects/smaaland/backend$ echo $GOPATH
/home/per/go
per@lex14:~/projects/smaaland/backend$ which akamai-api-gateway
/home/per/go/bin/akamai-api-gateway
per@lex14:~/projects/smaaland/backend$ akamai-api-gateway privacy-add --endpoint=764997 --version=30 -public --resource /performance
Updating privacy...... [FAIL]
json: cannot unmarshal object into Go struct field APIPrivacyResource.resources.methods of type []string
per@lex14:~/projects/smaaland/backend$`

Will try to debug...

**Comment by robertolopezlopez** [comment]
> Where is the download link?

If you expand the "Assets" section in the [given link](https://github.com/akamai/cli-api-gateway/releases/latest), you will find some precompiled binaries which you may use instead of having to compile this module manually :-)

![image](https://user-images.githubusercontent.com/1519467/162165675-60a67952-3fb3-4d31-bd71-e42f3e3b8f92.png)

Does this work for you ?

**Comment by per-garden** [comment]
Yes, I found it. Thank you!

It seems the error is thrown in `func callPrivacy(c *cli.Context) error {` at line 61 in command-privacy.go

**Comment by per-garden** [comment]
Downloaded ad tried suggested binary too:

`per@lex14:~/projects/smaaland/backend$ ~/junk/akamai-api-gateway-0.1.0-linuxamd64 privacy-add --endpoint=764997 --version=30 -public --resource /performance
Updating privacy...... [FAIL]
json: cannot unmarshal object into Go struct field APIPrivacyResource.methods of type []string
per@lex14:~/projects/smaaland/backend$`

**Comment by per-garden** [comment]
![smaaland1440](https://user-images.githubusercontent.com/1906176/162185290-6b86d265-491d-4462-a93b-2dfa73ae2aab.jpg)

**Comment by lkowalsk-akamai-com** [comment]
Hi @per-garden 
This does not look like an issue with Akamai-CLI, but the cli-api-gateway package directly. Please file the issue in queue for this package: https://github.com/akamai/cli-api-gateway/issues

**Comment by per-garden** [comment]
In api_privacy_settings.go the call

`rep := &APIPrivacySettings{}`

in GetAPIPrivacySettingsGetAPIPrivacySettings seems to return nothing and an error is thrown. This looks very much like a configuration error. What configuration is missing?

For the complete, compiled binary akamai-cli, I use an .edgerc with an API-client ID. I checked this ID again at control.akamai.com/apps/identity-management. It looks OK. And it works fine to e.g.upload API definitions. What is wrong?

**Comment by mgwoj** [comment]
Hi @per-garden 

As @lkowalsk-akamai-com wrote yesterday, please report this issue at the correct queue at https://github.com/akamai/cli-api-gateway/issues

**Comment by per-garden** [comment]
Done! Thanks!
