### ISSUE TITLE
Add ARM64 release download for Amazon Linux

### ISSUE THREAD

**Issue by bretlowery** [akamai/cli#149]
Please add an ARM64 release for Amazon Linux Graviton instance types.

WORKAROUND: The release must be built from source, which is time and cost-consuming.

**Comment by mgwoj** [comment]
Hi @bretlowery  ,

Adding arm64 support is in our roadmap, but we still do not have any specific dates yet. 

Regards,
Michal

**Comment by robertolopezlopez** [comment]
Closing this thread here, because there's already another one about the same topic

https://github.com/akamai/cli/issues/127
