### ISSUE TITLE
Windows Install Continually Prompts to "Install In Path"

### ISSUE THREAD

**Issue by waderoc** [akamai/cli#15]
When executing the Windows .exe (akamai-0.3.1-windowsamd64.exe), I am prompted to install the AkamaiCLI to my path.  I select a path for install, and the process completes.  

On subsequent attempts to run AkamaiCLI, I continue to be prompted to Install to path.  I can select "No", and use AkamaiCLI to install and use the Property/Purge modules .

**System Info**
![image](https://user-images.githubusercontent.com/8882946/29422205-84d7f2c2-8345-11e7-9182-7a84db348da3.png)

**Screenshot**

![image](https://user-images.githubusercontent.com/8882946/29422247-a39af59c-8345-11e7-8284-5eded727e9be.png)

**Comment by roberto-mardeni** [comment]
I have the same problem after installing v0.3.1, every time akamai cli executes it shows this

**Comment by dshafik** [comment]
This issue should be fixed in the next release of Akamai CLI (0.3.2)
