### ISSUE TITLE
(node:17719) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by veeramani29** [akamai/cli#152]
Getting error on macOS with akamai version 1.4.1

The below error

Getting Initialization status... /(node:17719) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at /Users/veeramanik/.akamai-cli/src/cli-edgeworkers/bin/src/cli-httpRequest.js:82:73
    at /Users/veeramanik/.akamai-cli/src/cli-edgeworkers/node_modules/akamai-edgegrid/src/api.js:102:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by Slonimskaia** [comment]
Hi @veeramani29 ,

Thank you for bringing this issue to our attention. Could you add steps to reproduce it and configuration script which you have used?

Best Regards,
Tatiana

**Comment by robertolopezlopez** [comment]
According to the error log, this looks rather an issue for cli-edgeworkers repository.

**Comment by Slonimskaia** [comment]
Closed as a not valid issue - cli-edgeworkers issue. @veeramani29 please open an issue in https://github.com/akamai/cli-edgeworkers repository if needed
