### ISSUE TITLE
`akamai update` sometimes has update errors

### ISSUE THREAD

**Issue by wongle** [akamai/cli#154]
When running `akamai update`, sometimes there are errors when updating packages.  

Running this command multiple times seems to eventually fix the errors.  

```
❯ akamai update
Attempting to update "edgekv" command... ... [FAIL]
 ERROR[0002] UPDATE ERROR: Unable to fetch updates (worktree contains unstaged changes) command=update
Unable to fetch updates (worktree contains unstaged changes)

❯ akamai update
Attempting to update "edgekv" command... ... [OK]
command "edgekv" already up-to-date
Attempting to update "edgeworkers" command... ... [OK]
command "edgeworkers" already up-to-date
Attempting to update "pipeline" command... ... [OK]
command "pipeline" already up-to-date
Attempting to update "property-manager" command... ... [OK]
command "property-manager" already up-to-date
Attempting to update "terraform" command... ... [FAIL]
 ERROR[0001] UPDATE ERROR: Unable to fetch updates (%!w(<nil>)) command=update
Unable to fetch updates (%!w(<nil>))

❯ akamai update
Attempting to update "edgekv" command... ... [OK]
command "edgekv" already up-to-date
Attempting to update "edgeworkers" command... ... [OK]
command "edgeworkers" already up-to-date
Attempting to update "pipeline" command... ... [OK]
command "pipeline" already up-to-date
Attempting to update "property-manager" command... ... [OK]
command "property-manager" already up-to-date
Attempting to update "terraform" command... ... [OK]
command "terraform" already up-to-date
```

Sorry -- I don't have any more debugging information, but happy to provide more details if possible.

**Comment by dstopka** [comment]
Hi @wongle!
Thank you for bringing this issue to our attention.

May I ask you to gather some logs the next time the reported problem occurs? It would help us with investigating your issue. For the logging, please refer to [this section in readme](https://github.com/akamai/cli#logging). 

Regards,
Darek

**Comment by robertolopezlopez** [comment]
Hi @wongle ,

This error looks like CLI is trying to do a `git pull` on `~/.akamai-cli/src/cli-edgekv/`, but someone has manually modified those files (CLI never does that).

> ❯ akamai update
> Attempting to update "edgekv" command... ... [FAIL]
>  ERROR[0002] UPDATE ERROR: Unable to fetch updates (worktree contains unstaged changes) command=update
> Unable to fetch updates (worktree contains unstaged changes)

In your second example, I would say that there was some network issue between your machine and github.

> Attempting to update "terraform" command... ... [FAIL]
>  ERROR[0001] UPDATE ERROR: Unable to fetch updates (%!w(<nil>)) command=update
> Unable to fetch updates (%!w(<nil>))

Could you please share more information and/or logs?

Kind regards,

Roberto

**Comment by robertolopezlopez** [comment]
hi @wongle ,

Could you please show us the output of `git status` on your `$HOME/.akamai-cli/src/cli-edgeworkers` directory? (And any other directory for which the update command is failing.)

Thank you

**Comment by robertolopezlopez** [comment]
@wongle : we have just released cli 1.5.2, which includes some improvements in the `akamai update` command. Do you mind to verify if it is fixing your issue?

**Comment by wongle** [comment]
Hi all -- apologies for the silence.  It seems that the issue happens intermittently, so I don't always catch it.

> This error looks like CLI is trying to do a `git pull` on `~/.akamai-cli/src/cli-edgekv/`, but someone has manually modified those files (CLI never does that).

This is strange, as I haven't touched any of the files within `~/.akamai-cli/`


Here's the output of `git status` on `$HOME/.akamai-cli/src/cli-edgeworkers`:
```
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

I'm currently on cli 1.5.1 and have just updated to cli 1.5.2 (via `brew upgrade`).

`akamai update` (on cli 1.5.2) showed no errors (and all packages were already up-to-date).  I'll likely need to wait until there are some package updates before potentially facing an error.  Will report back if there are any errors next time I run `akamai update`.

**Comment by lkowalsk-akamai-com** [comment]
@wongle we done some changes that we hope will fix this issue. I know it is hard to test without new versions of packages hence I'm closing this ticket and plese do not hasitate to reopen it if you encounter this problem again.
