### ISSUE TITLE
Docs need updated maybe? Is it AKAMAI_LOG or AKAMAI_CLI_LOG?

### ISSUE THREAD

**Issue by jeremy-daley-kr** [akamai/cli#155]
The docs are unclear...

See here:

https://github.com/akamai/cli#logging

**Comment by wzagrajcz** [comment]
Hello,
Thank You for spotting this issue. We will address it in a future release, most probably next month.

Regards,
Wojciech

**Comment by jeremy-daley-kr** [comment]
Thanks @wzagrajcz . Can you tell me which one it is though. I'm honestly not sure.

**Comment by wzagrajcz** [comment]
Hello,
Currently please use `AKAMAI_LOG` for setting the logging level and `AKAMAI_CLI_LOG_PATH` for setting the location of log file.

Regards,
Wojciech

**Comment by robertolopezlopez** [comment]
[Latest release](https://github.com/akamai/cli/releases/tag/v1.5.1) fixed the README.md logging information. Please reopen this issue if still unclear.

Regards,
Roberto
