### ISSUE TITLE
Error with credentials in Windows

### ISSUE THREAD

**Issue by roberto-mardeni** [akamai/cli#16]
I setup my credentials according to the guide and when I execute:

`akamai property retrieve <property name removed on purpose>`

I get the error below:

```
C:\Users\rmardeni\.akamai-cli\src\cli-property\node_modules\edgegrid\src\edgerc.js:69
    throw new Error('An error occurred parsing the .edgerc file. You probably specified an invalid section name.');
    ^

Error: An error occurred parsing the .edgerc file. You probably specified an invalid section name.
    at module.exports (C:\Users\rmardeni\.akamai-cli\src\cli-property\node_modules\edgegrid\src\edgerc.js:69:11)
    at EdgeGrid._setConfigFromObj (C:\Users\rmardeni\.akamai-cli\src\cli-property\node_modules\edgegrid\src\api.js:152:17)
    at new EdgeGrid (C:\Users\rmardeni\.akamai-cli\src\cli-property\node_modules\edgegrid\src\api.js:26:10)
    at new WebSite (C:\Users\rmardeni\.akamai-cli\src\cli-property\src\website.js:64:26)
    at main (C:\Users\rmardeni\.akamai-cli\src\cli-property\bin\akamaiProperty:499:20)
    at Object.<anonymous> (C:\Users\rmardeni\.akamai-cli\src\cli-property\bin\akamaiProperty:609:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

My username in my computer is **rmardeni** and the credentials were stored in **c:\users\rmardeni\.edgerc**, what is wrong with this?

**Comment by dshafik** [comment]
@roberto-mardeni the correct path would be `c:\users\rmardeni\.edgerc` - the entire filename is `.edgerc`, it's not a file extension.

Let me know if this helps.

**Comment by waderoc** [comment]
@roberto-mardeni are you passing the **--section** arg?  you need to use this to reference the section in .edgerc that you will use for authentication

**Comment by roberto-mardeni** [comment]
I shouldn't need to pass the section if the default one applies. Doesn't it?

Roberto Mardeni

**Comment by dshafik** [comment]
@roberto-mardeni the default depends on the command, for Akamai CLI for Property Manager, the default is `papi`, for Purge, it's `ccu`, and for Visitor Prioritization it's `cloudlets`.

**Comment by roberto-mardeni** [comment]
Wow, what a way to throw away standards.

Why would u design a credentials file to be used in this way? I guess nobody in Akamai understands what it means to define a simple to use CLI

I will try this out and report back

Roberto Mardeni

**Comment by dshafik** [comment]
@roberto-mardeni I understand this can be confusing, however, best security practices recommend that you minimize the attack surface area by using unique credentials for each application. Similarly, you should only grant read-only access when possible (it isn't with Akamai CLI). We consider each package it's own application when it comes to default credentials, although ideally, you would be even more granular in your implementation.

While it is _possible_ to create a single credential set with full access to all of Akamai's APIs, should those credentials be compromised that would open you to much more potential for damage than if you use discrete credentials for each task.

Having said that, we are still early in the life-cycle of Akamai CLI, and welcome your feedback on this particular issue and will incorporate it into our planning as we go forward.

**Comment by roberto-mardeni** [comment]
Using the **--section** parameter worked for me, so I can close this issue now.

I do think however that using a section named **default** should be an option, especially because you are not really minimizing the attack surface area by having to provide an additional parameter, you are just making it a little bit harder for anybody to use the CLI, especially because those credentials will be within the same **.edgerc** file.

Minimizing the attack surface area is an enterprise practice that you will not be able to effectively enforce this way and it should be at most a recommendation for users to adopt as best practice.

**Comment by felipemor** [comment]
Guys, how are you? I have this problem, but where should I put the --section flag ?
