### ISSUE TITLE
Bypass the user prompts

### ISSUE THREAD

**Issue by mshekharee** [akamai/cli#162]
In linux, installation of the Akamai cli is performed by downloading the binary file and moving it to /usr/loca/bin/akamai location.
Post this the user is prompted for scenarios such as:

-  "Akamai CLI can auto-update itself, would you like to enable daily checks? [Y/n]:  (Y/n)" 
- "Binary command(s) found, would you like to download and install it? (Y/n)"

This is fine if you are installing the binary manually and a user is present to approve these.
How do we automate this? We don't see flags that can be passed as arguments to bypass these options for automations

![bypass_installation_without_prompt](https://user-images.githubusercontent.com/70192286/182781168-19dc314d-5dd5-4faf-8305-bd5acf463813.jpg)
![bypass_akamai_prompt](https://user-images.githubusercontent.com/70192286/182781182-0877e139-b338-46f9-be75-b194c1cb2a6e.jpg)

**Comment by kaush-** [comment]
Hi @mshekharee,

Thank you for raising this issue with us. Have you tried using a pipeline with yes/no response? We recently had that fixed here https://github.com/akamai/cli/issues/136 and it might help you automate the prompt.

Let us know if it helps or if you are still facing any issues.

Regards,
Piyush
