### ISSUE TITLE
DXE-1864 CLI search is broken

### ISSUE THREAD

**Issue by cbullockaka** [akamai/cli#166]
akamai cli version 1.5.2

Trying to search for a module results in an error about "invalid character < ".

example:
$ akamai search purge
 ERROR[0000] SEARCH ERROR: unable to fetch remote Package List (invalid character '<' looking for beginning of value) command=search
unable to fetch remote Package List (invalid character '<' looking for beginning of value)

This happens consistently for this version across multiple operating systems as well as the akamai shell docker container

**Comment by lkowalsk-akamai-com** [comment]
Hi @cbullockaka , thanks for rising this issue. We were able to reproduce it and will be fixing it.

**Comment by lkowalsk-akamai-com** [comment]
Hi @cbullockaka this issue should be fixed now. Please check.

**Comment by cbullockaka** [comment]
@lkowalsk-akamai-com working as expected on 1.5.3, thanks so much!
