### ISSUE TITLE
unable to fetch remote Package List (invalid character '<' looking for beginning of value) command=search

### ISSUE THREAD

**Issue by simnow7** [akamai/cli#167]
Hi Team,

akamai search always says below error. Do you know why it is? My cli version is akamai version 1.5.2

hsim@sel-wpvvw:~$ akamai search diag
 ERROR[0001] SEARCH ERROR: unable to fetch remote Package List (invalid character '<' looking for beginning of value) command=search
unable to fetch remote Package List (invalid character '<' looking for beginning of value)
hsim@sel-wpvvw:~$ akamai search property
 ERROR[0000] SEARCH ERROR: unable to fetch remote Package List (invalid character '<' looking for beginning of value) command=search
unable to fetch remote Package List (invalid character '<' looking for beginning of value)

**Comment by lkowalsk-akamai-com** [comment]
Closing this as a duplicate -> https://github.com/akamai/cli/issues/166
