### ISSUE TITLE
Homebrew missing NodeJS

### ISSUE THREAD

**Issue by amesegue** [akamai/cli#173]
After installing Akamai CLI via brew, I wasn't able to install submodules:

```
% akamai install appsec  
Attempting to fetch command from https://github.com/akamai/cli-appsec.git... ... [OK]
Installing... ... [FAIL]
unable to locate runtime: Node.js. Please verify if the executable is included in your PATH
 ERROR[0001] unable to locate runtime: Node.js. Please verify if the executable is included in your PATH command=install
 ERROR[0001] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package
```

```
% akamai install property-manager
Attempting to fetch command from https://github.com/akamai/cli-property-manager.git... ... [OK]
Installing... ... [FAIL]
unable to locate runtime: Node.js. Please verify if the executable is included in your PATH
 ERROR[0001] unable to locate runtime: Node.js. Please verify if the executable is included in your PATH command=install
 ERROR[0001] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package
```

The issue was reproducible on both x86 and M1 after fresh install:

Darwin --redacted-- 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

Darwin --redacted--22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

After installing NodeJS via brew, submodules were installed successfully. I cannot say with 100% accuracy that either nodejs or another nodejs's brew requirement solved the issue thou.

`brew install nodejs`

```% akamai install property-manager
Attempting to fetch command from https://github.com/akamai/cli-property-manager.git... ... [OK]
Installing... ... [OK]
```

Would be nice to add NodeJS to the brew formula requirements since the most popular submodules depend on it.

**Comment by wzagrajcz** [comment]
Hello @amesegue 
Thanks for opening the issue. Both `appsec` and `property-manager` requires to have Node.js installed. So installing Node.js resolved the issue mentioned in Your message. However not all packages require Node to be installed; some require Python some does not have any requirements. 
We will assess the risks of adding such dependency on brew level and come back to You with information if we will implement it.

Best regards,
Wojciech

**Comment by lkowalsk-akamai-com** [comment]
Node is needed only for some subset of CLI packages. The same is with Python. Additionally, since some developers may need to have certain versions of Node (or Python) installed for different projects, we will not include Node/Python dependencies to be included in CLI. It is the developers responsibility to set up the environment to have it working with  specific CLI packages.
