### ISSUE TITLE
Akamai install error on dockerfile

### ISSUE THREAD

**Issue by villafen** [akamai/cli#179]
Hello, there are errors with akamai install on dockerfile

I get the following error when executed akamai install from dockerfile

`Step 8/8 : RUN yes | /usr/local/bin/akamai install purge
 ---> Running in 2fc9c092b2a4
unable to locate runtime: go. Please verify if the executable is included in your PATH
 ERROR[0000] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package
The command '/bin/sh -c yes | /usr/local/bin/akamai install purge' returned a non-zero code: 1`

But if I remove that line from dockerfile and execute the same once the image is build the install is completed without any issues

My dockerfile is the following 

```dockerfile
FROM ubuntu
USER root
RUN apt-get update -y \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
      wget ca-certificates
RUN wget -O ~/akamai https://github.com/akamai/cli/releases/download/v1.5.5/akamai-v1.5.5-linuxamd64 --no-check-certificate
RUN chmod +x ~/akamai
RUN mv ~/akamai /usr/local/bin/akamai
RUN echo $PATH
RUN yes | /usr/local/bin/akamai install purge
```

If you have any tips or fix it would be much appreciated

**Comment by majakubiec** [comment]
Hi @villafen,

The akamai cli, if the go compiler hasn't been found, prompts you if you would like to use a precompiled binary, but only if the cli is called from terminal (thats why it works from terminal and not from docker build).

You can force the binary install using `--force` flag as below.

```
RUN yes | /usr/local/bin/akamai install --force purge
```
