### ISSUE TITLE
CLI Update command

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli#18]
In the documentation, the command to update the CLI package is:
```bash
akamai upgrade
```

When I run the CLI and look for help, I get this:
```bash
akamai
Usage: 
   akamai [global flags] command [command flags] [arguments...]

Built-In Commands:
   help
   list
   get
   update
```

And I was able to update using the ```akamai update``` command. So maybe the documentation needs to be corrected. Please could you check?

**Comment by dshafik** [comment]
@akshayranganath the Upgrade command was added in 0.3.0, and is disabled when Homebrew is used to install (as homebrew itself manages the upgrades).

If you're running 0.3.0+ and did not use Homebrew, please reopen this ticket.
