### ISSUE TITLE
Cloudlets V3 API support?

### ISSUE THREAD

**Issue by srodgers-awaze** [akamai/cli#180]
I'm unable to list shared cloudlet policies at the moment as the CLI is using the V2 API:

(base) ➜  ~ akamai cloudlets list --cloudlet-type AS
+----+----------------------------------+----------------------------------------------------------+
|    | action                           | endpoint                                                 |
|----+----------------------------------+----------------------------------------------------------|
|  0 | AUDIENCE SEGMENTATION MATCH RULE | /api/v2/schemas/match_rule-AS-1.0.json                   |
|  1 | CREATE/CLONE POLICY VERSION      | /api/v2/schemas/create-nimbus_policy_version-AS-1.0.json |
|  2 | UPDATE POLICY VERSION            | /api/v2/schemas/update-nimbus_policy_version-AS-1.0.json |
|  3 | CREATE POLICY                    | /api/v2/schemas/create-policy.json                       |
|  4 | UPDATE POLICY                    | /api/v2/schemas/update-policy.json                       |
|  5 | CLONE POLICY                     | /api/v2/schemas/clone-policy.json                        |
+----+----------------------------------+----------------------------------------------------------+
...fetching policy list
0 policies found

Could v3 API support be added?

**Comment by pwongcha** [comment]
Do you get anything if you don't filter --cloudlet-type AS?
If not, could you please email me what account you are using? pwongcha@akamai.com

**Comment by pwongcha** [comment]
@srodgers-awaze I found your account and will investigate this because I don't get the result locally either.
@wzagrajcz This issue can go to cli-cloudlets and not cli-docker.

**Comment by srodgers-awaze** [comment]
Thanks 👍

**Comment by pwongcha** [comment]
repo is updated.  can you run `akamai update cloudlets` and verify?
