### ISSUE TITLE
DXE-3139 Additional documentation needed for use of python-based sub-commands

### ISSUE THREAD

**Issue by dvogel** [akamai/cli#181]
The README mentions the need to have the python `venv` module available. Some packages, such as akamai/cli-cloudlets document in their README steps for installing into a virtualenv. However these are incompatible. As a result, on systems supporting PEP668 users attempting to run `akamai install cloudlets` are greeted by an error instructing them to use a virtualenv. From browsing the source, I cobbled together the paths expected by the tool. These or something like it should probably be added to the README.

```
mkdir -p $HOME/.akamai-cli/venv
python3 -mvenv $HOME/.akamai-cli/venv/cli-cloudlets
akamai install cloudlets
```

**Comment by mimazaka** [comment]
Hello @dvogel,

Thank you for mentioning this issue, we will take a look on it and decide on which level README file should be updated ( main cli repo or it should be added to specific `cli-_type_` ) .

Regards,
Michał

**Comment by skearney-akamai** [comment]
Hiya @dvogel, 

Thanks for bringing this up. As this library supports more than just Python, we lean on Python's instructions for environment set up. All of the Python dependency information is on our [README](https://github.com/akamai/cli/#system-dependencies-for-python-based-packages). 

There's also no particular place the environment needs to be; it just needs to be running.
