### ISSUE TITLE
Cloudlets and SSL certs

### ISSUE THREAD

**Issue by Firenzzz** [akamai/cli#186]
Dear Akamai team,

At the company I work they intercept our SSL comms. I didn't have a problem with GTM and Purge modules so far, but Cloudlets throw an SSL error for obvious reasons. Can you add an option to ignore that?

Also, can we have CSV support for ER policies?

Thank you!

**Comment by mstojanowski** [comment]
Dear @Firenzzz,

The issue you describe seems to be related to `cli-cloudlets`, not to `cli` it selves. Could you please move the ticket there?

Regards,
Marcin

**Comment by Firenzzz** [comment]
Yeah.

For some reason I had a tab with issues of cli-cloudlets originally and still managed to erroneously post it here. 

Thanks 😆
