### ISSUE TITLE
Symmantec Error

### ISSUE THREAD

**Issue by nextprojectawesome** [akamai/cli#19]
A coworker got a ws.reputation.1 popup from Symmantec blocking/deleting for akamai0.3.2-windowsamd64.exe

I looked it up and you can get the exe whitelisted

https://submit.symantec.com/whitelist/isv/

**Comment by dshafik** [comment]
@nextprojectawesome Hi, we are aware of this issue and are currently working on signing the binaries to avoid this issue — unfortunately white-listing wouldn't be a great option and it's per-binary and with the frequent release cycle of pre-1.0 software it's just not feasible.

This should be resolved in the next few weeks.

Thanks for your report!
