### ISSUE TITLE
DXE-3518 akamai search not up to date

### ISSUE THREAD

**Issue by michfuer** [akamai/cli#192]
The `akamai search` command appears to use this list for searching packages https://github.com/akamai/cli/blob/master/pkg/commands/package_list/package-list.json

There are some packages not found in search that are available to install, e.g. https://github.com/akamai/cli-etp

```
$ akamai search etp
Results Found: 0
```

```
$ akamai install etp
Attempting to fetch command from https://github.com/akamai/cli-etp.git... [OK]
Installing... [OK]
```

Same problem with https://github.com/akamai/cli-mfa

The reverse issue also exists where some packages in `package-list.json` don't exist anymore, e.g. https://github.com/akamai/cli-auth

```
$ akamai search auth
Results Found: 1

Package: Authentication [auth]
  Command: auth 
  Version: 0.0.3
  Description: Interface for Akamai Edgegrid Authentication


Install using "akamai install [package]".
```

```
$ akamai install auth
Attempting to fetch command from https://github.com/akamai/cli-auth.git... [FAIL]
 ERROR[0000] Package Is Not Available. Supported Packages Can Be Found Here: Https://Techdocs.Akamai.Com/Home/Page/Products-Tools-A-Z command=install
 ERROR[0000] INSTALL ERROR: Package is not available. Supported packages can be found here: https://techdocs.akamai.com/home/page/products-tools-a-z command=install
Package is not available. Supported packages can be found here: https://techdocs.akamai.com/home/page/products-tools-a-z
```

Please update the `package-list.json` and/or `akamai search` to match what's actually available.

It would also be nice to have a canonical page listing the available packages. For instance I can do a search of the akamai org in github e.g. https://github.com/search?q=topic%3Aakamai-cli+org%3Aakamai&type=Repositories&p=1

but not all the repos have the `akamai-cli` topic set, e.g. https://github.com/akamai/cli-cloudlets

Thanks!

**Comment by lkowalsk-akamai-com** [comment]
Hi @michfuer, this issue should be fixed in recent release.
