### ISSUE TITLE
how to upgrade installed akamai cli version 0.3.2 to 0.4.0? in linux rhel

### ISSUE THREAD

**Issue by rageshns** [akamai/cli#24]
![image](https://user-images.githubusercontent.com/507781/30543365-80fc19fc-9ca0-11e7-8832-a688dcd6c6ee.png)

**Comment by dshafik** [comment]
Can you tell me if this has been resolved along with #23 ?

**Comment by dshafik** [comment]
@rageshns can I get an update on this?

**Comment by dshafik** [comment]
Closing this due to no response.
