### ISSUE TITLE
Current version?

### ISSUE THREAD

**Issue by ilovezfs** [akamai/cli#28]
Based on https://github.com/akamai/cli/releases and https://github.com/akamai/cli/releases/latest I cannot tell if 0.4.1 or 0.4.2 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by dshafik** [comment]
@ilovezfs we're working through some release process stuff on our end regarding code signing, I'll be sure to bump the homebrew formula when 0.4.2 (or whatever does come next) is ready.

Thanks for being on top of this!

**Comment by ilovezfs** [comment]
@dshafik thanks for your response :)

>Thanks for being on top of this!

No problem. More than half the time when there's a newer tag not marked as a release, upstream actually intends for it to be a release. hehe
