### ISSUE TITLE
Unable to update the Property if existing property did not have hostnames

### ISSUE THREAD

**Issue by ctuppad** [akamai/cli#29]
HI,

The following scenarios does not seem to be working.
Step 1: Create a property using CLI without hostname.
Step 2: Modify the property with hostname using CLI. This throws an error and does not add the hostname. ( When checked the code, it seems while adding hostname it first tries to retrieve existing set of hostnames and then add into the list. If, there are no existing hostnames: code does not fetch existing hostname: null and hence throws error). If the existing property has a hostname, while updating new hostname via CLI - it works.
PFA the use case.

<img width="1066" alt="screen shot 2017-12-07 at 6 07 42 pm" src="https://user-images.githubusercontent.com/34309060/33715739-9d70499c-db79-11e7-965d-32d9ee125012.png">

**Comment by synedra** [comment]
I'll take a look at this, thanks!

**Comment by dshafik** [comment]
Moved to the [akamai/cli-property](/akamai/cli-property) repo as akamai/cli-property#73
