### ISSUE TITLE
Documentation of .edgerc sections

### ISSUE THREAD

**Issue by dhambali** [akamai/cli#32]
[alerts], [ccu], [papi], [default] are commonly known.

I've been able to discover [billingusage], [billingcenter], [cloudlet], [live], and [gtm] by looking through some python scripts.

Is there a document that shows the relationship of .edgerc sections to each service name in API Authorizations?

For example:

[papi] can have Property Manager as well as User Admin APIs.

![image](https://user-images.githubusercontent.com/1854558/35599111-073b8fb2-05dc-11e8-803a-d706521bba88.png)

As a new user of the CLI, it has been challenging to figure out which authorizations correspond with which .edgerc sections.

**Comment by partamonov** [comment]
As far as I saw, there are 3 types of credentials.

1. General API, which can be used for almost all services (level of access controlled via roles for client)
1. Netstorage API
1. Purge API

**Comment by synedra** [comment]
The edgerc section is governed by the individual command, so the help for that command should probably include the grant name for completeness.  Go ahead and open issues for the individual commands where you see the need and we'll get to them.

**Comment by dshafik** [comment]
The `.edgerc` file is in INI format, which means you have:

```ini
[section-name]
key=value
key2=value
```

The `[section-name]` is used to determine the correct set of credentials to use for the particular application, and in this case Akamai CLI for Visitor Prioritization has set the default `section-name` to `cloudlets` which you do not have defined. You can specify a section to use with the `--section` flag.

We are currently discussing changing all packages to use `default`, by default.

**Comment by paulbeattie** [comment]
👍 on this issue. It seems counterintuitive to duplicate creds across multiple different sections when you've got a default in there…

**Comment by cdenneen** [comment]
Why don't all fallback to default if that specific section doesn't exist?
Or fix so everything uses [default]

Having to duplicate in the .edgerc or type --section default is a bit of annoying.

**Comment by robertolopezlopez** [comment]
CLI itself does not make use of any `.edgerc` credentials. Instead, this is handled by the `cli-*` packages. Please, create this issue in the desired package repository.

Regards,

Roberto
