### ISSUE TITLE
Go(may be all others) builded plugins should take version from cli.json

### ISSUE THREAD

**Issue by partamonov** [akamai/cli#38]
In my plugins I now use version variable which I pass during build process.

```shell
go build -ldflags="-s -w -X main.version=0.0.8"
```

May be it will good idea to take version from `cli.json` and paste the value during building the binary?

**Comment by dshafik** [comment]
I like this @partamonov, I came across this idea a few weeks back but hadn't put them together. I don't think we can extend this to other languages however. I also need to investigate what will happen if the variable is not defined.

**Comment by partamonov** [comment]
It will just skip version. This is what happens now when I install my plugins. Also another not related to `go` - may be it will be useful to add option to force download binary, but not build locally

**Comment by robertolopezlopez** [comment]
Hi @partamonov: all recent CLI releases take required go/python/node version from `cli.json`. Thus I am closing this issue ;-)

Please do not hesitate on reopening if you have further concerns.

Regards,

Roberto
