### ISSUE TITLE
Certificate Error with private Repo

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli#4]
While i try to add a command using CLI get using a private repo, i see the below certificate error, looks like the client is expecting a CA signed Cert.

./akamai get https://***.***.***/users/****/repos/*******/
Attempting to fetch command...... [FAIL]
Unable to clone repository: Get https://***.***.***/users/****/repos/*******/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority

**Comment by dshafik** [comment]
@vreddhi we currently do not support client (x509) certificates, and recommend using SSH instead.
