### ISSUE TITLE
install of ruby-based plugins fails, but without error

### ISSUE THREAD

**Issue by rajiv** [akamai/cli#40]
on systems with ruby installed, but no bundler gem, installing of ruby-based cli plugins fails without notifying the user. the plugin appears to install successfully, but then is not usable because all the dependent gems are missing.

this is affecting macOS users. macOS version 10.12.6 (and earlier) include `/usr/bin/ruby` and `/usr/bin/gem` but not `/usr/bin/bundler` or `bundler` in any default PATH location. the bundler gem is not installed by default.

the issue seems to be that `installRuby` in `package_ruby` correctly returns `false` but then back in `installPackageDependencies` in `command_install`, the process does not stop execution if `success` is `false`. this is likely affecting other languages as well besides ruby.

`akamai install` should fail if it detects a `Gemfile` in the plugin source, but no `bundle` command installed.

```
$ akamai --version
akamai version 0.5.1
 $ akamai install rajiv/akamai-cli-certs
Attempting to fetch command from https://github.com/rajiv/akamai-cli-certs.git...... [OK]
Disclaimer: You are installing a third-party package, subject to its own terms and conditions. Akamai makes no warranty or representation with respect to the third-party package.
Installing.... 
Available Commands:

  help
    Displays help information
  list
    Displays available commands
  install (alias: get)
    Fetch and install packages from a Git repository.
  uninstall
    Uninstall package containing <command>
  update
    Update one or more commands. If no command is specified, all commands are updated
  certs (alias: cps)
    Manage Secure CDN certificates

See "akamai help [command]" for details.
$ akamai certs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- akamai/api/cps (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rmanglan/.akamai-cli/src/akamai-cli-certs/bin/akamai-certs:2:in `<main>'
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.0)
CFPropertyList (2.2.8)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

**Comment by dshafik** [comment]
This issue has been resolved during the course of refactoring installation and will be available in the next release (or if you compile from master):

<img width="332" alt="shell" src="https://user-images.githubusercontent.com/58074/38018845-ee1cb9f4-322a-11e8-87bd-632e994564ec.png">
