### ISSUE TITLE
Improve the Docker Container

### ISSUE THREAD

**Issue by dshafik** [akamai/cli#43]
Currently there are several issues with the Docker container:

- Only cli-property and cli-purge packages are included
- Use of `ENTRYPOINT` makes calling `akamai` directly difficult (you must use: `docker run -v $HOME/.edgerc:/root/.edgerc --entrypoint "akamai" akamaiopen/cli # other arguments for the akamai command`
- Currently it's not possible to use `docker run` followed by one or more calls to `docker exec`

Ideally we want the experience to be:

```
$ docker run -ti -v $HOME/.edgerc:/root/.edgerc akamaiopen/cli akamai help
```

or:

```
$ docker run -d -v $HOME/.edgerc:/root/.edgerc akamaiopen/cli
$ docker exec akamai help
$ docker exec akamai install foo
$ docker exec akamai foo
```

Additionally, as noted in #25, we should slim the container down as much as we can.

**Comment by lkowalsk-akamai-com** [comment]
Hi, we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
