### ISSUE TITLE
install failing with a cryptic message

### ISSUE THREAD

**Issue by videoguy** [akamai/cli#48]
I installed akamai cli on windows 10. Then issued the following command.

>akamai install netstorage

I see the following spew. I am running this on a box that needs proxy credentials to access internet.
_Attempting to fetch command from https://github.com/akamai/cli-netstorage.git...... [OK]
Installing...... [OK]
Unable to locate Node.js runtime
Binary command(s) found, would you like to try download and install it? (Y/n): Y
Downloading binary...... [FAIL]
Unable to download binary: Unable to locate Node.js runtime_

**Comment by dshafik** [comment]
@videoguy,

I believe the issue was with the Akamai CLI for NetStorage package, and should be fixed.

Let me know if this solves your issue?

**Comment by videoguy** [comment]
I think it is proxy issue. Once I passed proxy info on the command line, it seemed to have worked.

akamai --proxy corp-proxy-usa:80 install netstorage
Attempting to fetch command from https://github.com/akamai/cli-netstorage.git...... [OK]
Installing...... [OK]
Unable to locate Node.js runtime
Binary command(s) found, would you like to try download and install it? (Y/n): Y
Downloading binary...... [OK]

Installed Commands:

  config
    Manage configuration
  help
    Displays help information
  install (alias: get)
    Fetch and install packages from a Git repository.
  list
    Displays available commands
  netstorage
    Interface for Akamai NetStorage
  search
    Search for packages in the official Akamai CLI package repository
  uninstall
    Uninstall package containing <command>
  update
    Update one or more commands. If no command is specified, all commands are updated
  upgrade
    Upgrade Akamai CLI to the latest version

See "akamai.exe help [command]" for details.

**Comment by dshafik** [comment]
@videoguy it looks like this is resolved, can I close the issue?
