### ISSUE TITLE
Issue running Docker container: /opt/bin/akamai: cannot execute binary file

### ISSUE THREAD

**Issue by jernejz5** [akamai/cli#54]
After running command below I get an error.
```
➜ docker run -ti --rm  akamaiopen/cli akamai
/opt/bin/akamai: /opt/bin/akamai: cannot execute binary file
```

**Comment by lkowalsk-akamai-com** [comment]
Hi @jernejz5 , we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
