### ISSUE TITLE
Docker setup ignores my choice about not installing CLI to the PATH

### ISSUE THREAD

**Issue by jernejz5** [akamai/cli#55]
![image](https://user-images.githubusercontent.com/2420150/42559452-6e9559f8-84f4-11e8-9869-a7f602d5d527.png)

**Comment by lkowalsk-akamai-com** [comment]
Hi @jernejz5 , we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
