### ISSUE TITLE
Docker upgrade to new version fails

### ISSUE THREAD

**Issue by jernejz5** [akamai/cli#56]
![image](https://user-images.githubusercontent.com/2420150/42559653-fde5b274-84f4-11e8-8425-91161fd4d1f1.png)

**Comment by lkowalsk-akamai-com** [comment]
Hi @jernejz5 , we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
