### ISSUE TITLE
CLI package list not available

### ISSUE THREAD

**Issue by tmaher** [akamai/cli#59]
It appears that the CLI's package list URL is broken. Using a fresh download of v1.0.2 of the CLI (macOS 10.13.6 w/Homebrew), I get the following error...
```
tom.maher@goibniu:~$ akamai search property
Unable to fetch remote Package List (invalid character '<' looking for beginning of value)
```
[Checking into the code (command_search.go, line 73)](https://github.com/akamai/cli/blob/43aaabbf3bbd58df4a7f4f7880c0556bd17166e2/command_search.go#L73), the URL appears to be [https://developer.akamai.com/cli/package-list.json](https://developer.akamai.com/cli/package-list.json), which 302's to [https://developer.akamai.com/legacy/cli/package-list.json](https://developer.akamai.com/legacy/cli/package-list.json), which 302's to [https://developer.akamai.com/error](https://developer.akamai.com/error)

So, did this move?

**Comment by justinrummel** [comment]
@tmaher This should now be fixed.  Thanks for bring it to our attention! 

``` bash
jrummel@macbook ~> curl -sI "https://developer.akamai.com/cli/package-list.json" | grep "HTTP/"
HTTP/2 200

jrummel@macbook ~> akamai search property
Results Found: 1

Package: Property Manager [property]
  Command: property
  Version: 1.0.2
  Description: Manage configurations for Akamai properties


Install using "akamai install [package]".
```
