### ISSUE TITLE
Multiple instances of CLI

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli#6]
This isnt an issue. A question/feedback.

Calling akamai get <repo> will download and install the command repository to the $HOME/.akamai-cli directory.

What if i want to have multiple separate instances of akamai CLI. As we are using $HOME here, looks like it will be shared across instances. Do you think its better to update/change to a relative path of CLI installed folder?

**Comment by dshafik** [comment]
@vreddhi we don't anticipate needing multiple versions of the same command installed.

I had originally made `akamai` search the users `$PATH` (with `$HOME/.akamai-cli` added to the end) which would allow you to override commands by manipulating `$PATH` but it was removed in favor of simplifying.

I could see adding an `AKAMAI_CLI_HOME` environment variable that overrides the use of `$HOME` if there is justification for doing so. At the current stage of the project, where everything is brand new, and backwards compatibility breaks are non-existent, it just isn't necessary.

Do you have a use-case?
