### ISSUE TITLE
Cannot install appsec: Downloading binary fail

### ISSUE THREAD

**Issue by tadhgpearson** [akamai/cli#62]
When I try to install appsec, I get the following issue

```
$ akamai install appsec
Attempting to fetch command from https://github.com/akamai/cli-appsec.git...... [OK]
Downloading binary...... [FAIL]
... [FAIL]
exit status 1
```

I'm connected to the internet, etc. and _akamai install property_ worked fine.

What's going wrong? How can I get a more verbose log of the install?

**Comment by justinrummel** [comment]
Hello @tadhgpearson, I'm going to guess that Node.js is not installed or old.  Can you run `node --version` and tell me what version you are running.  I have:

```
ladmin@macbook ~> node --version
v10.11.0
```

**Comment by tadhgpearson** [comment]
Nope - I'm running the latest version: 

```
$ node --version
v10.11.0
```

**Comment by synedra** [comment]
Are you still getting this error?  It's actually a python based application.  Could you give me your python version?

Weirdly it looks like it's trying to install the binary and failing, and I'm not sure why that would be.  I can do some more digging once I know that it's still failing.

Thanks

**Comment by partamonov** [comment]
For me it is even not trying to get binary from `install` command

```shell
akamai install appsec --force
Attempting to fetch command from https://github.com/akamai/cli-appsec.git...... [OK]
Installing...... [FAIL]
Unable to locate Node.js runtime
```

But if I just wget binary from repository it works fine
```shell
wget https://github.com/akamai/cli-appsec/releases/download/0.1.0/akamai-appsec-0.1.0-linux-amd64

./akamai-appsec-0.1.0-linux-amd64 --help
Usage: akamai appsec <command> [options]

Commands:
  configs                   List all available configurations.
```

It looks like something is broken in installer or installer cannot see binaries.

I can install `cli-property` just fine without any issue, even without node js installed

**Comment by dshafik** [comment]
This particular package _is_ written using node.js, and while there are binaries available on GitHub, they are not included in the [cli.json](https://github.com/akamai/cli-appsec/blob/master/cli.json) configuration, so the CLI cannot find them.

_However_, we are currently unable to sign these binaries on macOS due to an issue with how the binary is built. This means that they are not acceptable for our needs, and **should not** be included in the cli.json. We are currently working on a new binary packaging, which will hopefully resolve this in the near future.

**Comment by tadhgpearson** [comment]
@synedra  - I'm running Python` 2.7.10`

**Comment by dshafik** [comment]
@tadhgpearson @synedra was mistaken, it's Node; specifically 7.0+.

**Comment by dshafik** [comment]
@tadhgpearson is this still an issue for you?
