### ISSUE TITLE
Updates to https://developer.akamai.com/cli/package-list.json should trigger a new build of the Docker image

### ISSUE THREAD

**Issue by adedommelin** [akamai/cli#69]
Right now, the image is rebuilt only when new commits are pushed to this repo.
As we're including CLI modules in the image, updates to the packages list should also trigger a build.

**Comment by javiergarza** [comment]
Thanks a great idea Alexandre! @dshafik what do you think?

**Comment by lkowalsk-akamai-com** [comment]
Hi @adedommelin , we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
