### ISSUE TITLE
failing to read .edgerc

### ISSUE THREAD

**Issue by atecce** [akamai/cli#70]
<img width="943" alt="screen shot 2018-12-07 at 8 58 07 am" src="https://user-images.githubusercontent.com/10567112/49651831-4a65e000-f9fe-11e8-8ac0-2b342b00ebea.png">

highly confident my `~/.edgerc` is correct considering that i can use [this](https://github.com/akamai/AkamaiOPEN-edgegrid-golang)

**Comment by justinrummel** [comment]
In `akamai property help`, the default section is "papi".  You may need to specify the section name such as "default" (depending how you labeled your .edgerc file).

``` bash
Command options:
  --config <config>    Config file                [file] [default: /Users/jrummel/.edgerc]
  --section <section>  Config section                             [string] [default: papi]
  --debug <debug>      Turn on debugging.                                        [boolean]
  --help               Show help                                [commands: help] [boolean]
  --version            Show version number                   [commands: version] [boolean]
```

**Comment by atecce** [comment]
tyvm
