### ISSUE TITLE
Can't remove SRV record.

### ISSUE THREAD

**Issue by yuanchang-akm** [akamai/cli#71]
When removing SRV record using dns module. There's  an error.

> akamai dns --edgerc ./dns_cred.txt rm-record SRV 20181212.yctest.xyz --name  _sip._tls --target ipcenter001.20181212.yctest.xyz --priority 0 --weight 0 --port 443

Removing SRV record.... panic: interface conversion: interface {} is uint, not uint16

goroutine 1 [running]:
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).findSrvRecord(0xc4200e4d80, 0xc420190ad8, 0x140174b, 0x3, 0x1)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:1480 +0x695
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).FindRecords(0xc4200e4d80, 0x1401760, 0x3, 0xc420190ad8, 0xc420190ce0, 0xc4200e2600, 0x20)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:843 +0x44e
main.cmdRmRecord(0xc42017a2c0, 0x101010100, 0xc42017a2c0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/command_rm_record.go:100 +0xc63
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.HandleAction(0x1386100, 0x141a0f8, 0xc42017a2c0, 0xc4200ba400, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x1401760, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200a6d00, 0xc42017a000, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:379 +0xa10
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.startApp(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:298 +0x8d9
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:98 +0x1246
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).Run(0xc4200a6b60, 0xc4200b4000, 0x10, 0x10, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/akamai-dns.go:37 +0xcf

**Comment by yuanchang-akm** [comment]
Still have this issue after updating to the latest version.

> akamai dns --edgerc ./dns_cred.txt rm-record SRV 20181212.yctest.xyz --name  _sip._tls --target ipcenter001.20181212.yctest.xyz. --priority 0 --port 80 --ttl 300 --weight 0

Removing SRV record..... panic: interface conversion: interface {} is uint, not uint16

goroutine 1 [running]:
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).findSrvRecord(0xc4200e2d80, 0xc420190ad8, 0x140174b, 0x3, 0x1)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:1480 +0x695
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).FindRecords(0xc4200e2d80, 0x1401760, 0x3, 0xc420190ad8, 0xc420190cc0, 0xc4200de7e0, 0x27)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:843 +0x44e
main.cmdRmRecord(0xc42017a2c0, 0x10101010100, 0xc42017a2c0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/command_rm_record.go:100 +0xc63
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.HandleAction(0x1386100, 0x141a0f8, 0xc42017a2c0, 0xc4200ba400, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x1401760, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200a6d00, 0xc42017a000, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:379 +0xa10
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.startApp(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:298 +0x8d9
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:98 +0x1246
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).Run(0xc4200a6b60, 0xc4200b4000, 0x12, 0x12, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/akamai-dns.go:37 +0xcf

**Comment by yuanchang-akm** [comment]
Should I open a new Issue about this problem?

**Comment by dshafik** [comment]
@yuanchang-akm can you try now?

**Comment by yuanchang-akm** [comment]
@dshafik 
Thank you for your reply.
I updated it to the latest version and tried again.
There is still an error here.

> akamai dns --edgerc ./dns_cred.txt rm-record SRV 20181212.yctest.xyz --name  _sip._tls --target ipcenter001.20181212.yctest.xyz. --priority 0 --port 80 --ttl 300 --weight 0
Removing SRV record.... panic: interface conversion: interface {} is uint, not uint16

goroutine 1 [running]:
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).findSrvRecord(0xc4200e2d80, 0xc420190ad8, 0x140174b, 0x3, 0x1)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:1480 +0x695
github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).FindRecords(0xc4200e2d80, 0x1401760, 0x3, 0xc420190ad8, 0xc420190cc0, 0xc4200de7e0, 0x27)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:843 +0x44e
main.cmdRmRecord(0xc42014e6e0, 0x10101010100, 0xc42014e6e0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/command_rm_record.go:100 +0xc63
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.HandleAction(0x1386100, 0x141a0f8, 0xc42014e6e0, 0xc4200ba400, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x1401760, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200a6d00, 0xc42014e420, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:379 +0xa10
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.startApp(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:298 +0x8d9
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x14031d6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:98 +0x1246
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).Run(0xc4200a6b60, 0xc4200b4000, 0x12, 0x12, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:255 +0x6a0
main.main()
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/akamai-dns.go:37 +0xcf

**Comment by dshafik** [comment]
@yuanchang-akm how are you updating?

**Comment by yuanchang-akm** [comment]
@dshafik 
First I updated akamai cli by brew.
And then I updated all the modules using  "akamai update" command.

**Comment by dshafik** [comment]
@yuanchang-akm can you try an explicit `akamai update dns`, and if that doesn't work, try `akamai uninstall dns && akamai install dns`?

**Comment by yuanchang-akm** [comment]
@dshafik  
I have tried it , but it still have an error. 
Can you remove SRV record using CLI with full option like this?
--name _sip._tls --target ipcenter001.20181212.yctest.xyz --priority 0 --weight 0 --port 443

**Comment by dshafik** [comment]
@yuanchang-akm yes, can you confirm that `akamai dns --version` shows 0.2.0? Also, what OS are you on?

**Comment by yuanchang-akm** [comment]
@dshafik 
It shows 0.1.0. Even I uninstall it and reinstall it , it is still version 0.1.0.
Is there any problem in the tool that could not get the latest version?
The OS is Mac OS X Mojave.

**Comment by yuanchang-akm** [comment]
@dshafik 
This problem need to be solved as soon as possible.
Could you please confirm this?
We can't update dns to 0.2.0.

**Comment by yuanchang-akm** [comment]
@dshafik 
We found that there's a new version for dns module.
But after updating to the latest version, we can not even use the function which hadn't has problem.
[10:12] ~ > akamai dns -version
[10:12] ~ > akamai dns -help
[10:14] ~ > 

No response for commands.

**Comment by yuanchang-akm** [comment]
@justinrummel 
Thank you for your help.
After installing dep by brew, it works well.
Before reporting this problem, we can use CLI without installing golang env and dep.
Is there a good way for us to upgrade and use the latest dns module without installing golang env and dep?

**Comment by justinrummel** [comment]
I’ll work with @dshafik now that we know the issue. Thanks for confirming!

**Comment by yuanchang-akm** [comment]
@justinrummel 
Thank you very much.
This tool is working on client's server, we need one command to get the latest version through:
akamai update.
Could you please give me a schedule for resolving this problem?

**Comment by yuanchang-akm** [comment]
@dshafik 
Thank you very much for your help.
It works fine now.

**Comment by dshafik** [comment]
@yuanchang-akm thanks for the confirmation, I'll go ahead and close this now.
