### ISSUE TITLE
Verify local clock is in sync with the server

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli#72]
If the system clock drifts more than 30 seconds apart from the OPEN API Edgegrid server, the user will get an authentication error. This error not caught in almost any CLI package (most return very ugly errors) so instead of having to patch all CLI modules it would be great if the main CLI could verify this.

You can easily test if your clock is in sync by using Akamai's Time reference server time.akamai.com. See https://developer.akamai.com/legacy/learn/Akamai_Time_Reference/AkamaiTimeReference.html

For example in MacOS or linux you could run this command to verify how far apart your local clock is:
AA=`curl -q http://time.akamai.com/`;BB=`date +%s`;echo "Your time drift is: $(($AA-$BB)) seconds"

**Comment by frankthelen** [comment]
Cool. Thanks for sharing. Did you mean `curl -sS`? From man pages:
```
-q (skip .curlrc)
-s --silent
-S --show-error
```
