### ISSUE TITLE
CLI Docker image runs as root user

### ISSUE THREAD

**Issue by dmcallis1** [akamai/cli#73]
The current CLI Docker image runs processes as a root user (default) which presents a potential security concern. Furthermore, frameworks like Openshift specifically restrict containers running as root as part of their security model:

https://hub.docker.com/r/openshift/origin-custom-docker-builder/

Can the image be updated to assume it will be run as a non-root user?

**Comment by lkowalsk-akamai-com** [comment]
Hi @dmcallis1 , we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
