### ISSUE TITLE
Trace not showing details

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli#75]
Seems the trace is not showing enough information to allow debugging. Can we please ensure trace displays enough information to identify what's going on the backend? thanks!

In the example below the property package fails to install but you can't see any details even with trace on.

$ export AKAMAI_LOG=TRACE
$ akamai update
Attempting to update "api-gateway" command...
Attempting to update "api-gateway" command...... [OK]

command "api-gateway" already up-to-date
Attempting to update "api-keys" command...
Attempting to update "api-keys" command...... [OK]

command "api-keys" already up-to-date
Attempting to update "api-security" command...
Attempting to update "api-security" command...... [OK]

command "api-security" already up-to-date
Attempting to update "appsec" command...
Attempting to update "appsec" command...... [OK]

command "appsec" already up-to-date
Attempting to update "auth" command...
Attempting to update "auth" command...... [OK]

command "auth" already up-to-date
TRACE[0000] Python binary found: /usr/local/bin/python3
TRACE[0000] Pip binary found: /usr/local/bin/pip3
Attempting to update "cps" command...
Attempting to update "cps" command...... [OK]

command "cps" already up-to-date
Attempting to update "dns" command...
Attempting to update "dns" command...... [OK]

command "dns" already up-to-date
TRACE[0001] Python binary found: /usr/local/bin/python3
TRACE[0001] Pip binary found: /usr/local/bin/pip3
Attempting to update "firewall" command...
Attempting to update "firewall" command...... [OK]

command "firewall" already up-to-date
Attempting to update "gss-cli" command...
Attempting to update "gss-cli" command...... [OK]

command "gss-cli" already up-to-date
TRACE[0004] Python binary found: /usr/bin/python
TRACE[0004] Pip binary found: /usr/local/bin/pip2
Attempting to update "image-manager" command...
Attempting to update "image-manager" command...... [OK]

command "image-manager" already up-to-date
Attempting to update "netstorage" command...
Attempting to update "netstorage" command...... [OK]

command "netstorage" already up-to-date
Attempting to update "network-experience-analytics" command...
Attempting to update "network-experience-analytics" command...... [OK]

command "network-experience-analytics" already up-to-date
Attempting to update "pipeline" command...
Attempting to update "pipeline" command...... [OK]

command "pipeline" already up-to-date
Attempting to update "property" command...
Attempting to update "property" command...... [FAIL]

Unable to fetch updates
$

**Comment by synedra** [comment]
Have you tried DEBUG?

I think that works as well.

K

**Comment by javiergarza** [comment]
I see even less info using DEBUG. @synedra Do you see more info than what displayed below?

$ export AKAMAI_LOG=DEBUG
$ akamai update
Attempting to update "api-gateway" command...
Attempting to update "api-gateway" command...... [OK]

command "api-gateway" already up-to-date
Attempting to update "api-keys" command...
Attempting to update "api-keys" command...... [OK]

command "api-keys" already up-to-date
Attempting to update "api-security" command...
Attempting to update "api-security" command...... [OK]

command "api-security" already up-to-date
Attempting to update "appsec" command...
Attempting to update "appsec" command...... [OK]

command "appsec" already up-to-date
Attempting to update "auth" command...
Attempting to update "auth" command...... [OK]

command "auth" already up-to-date
Attempting to update "cps" command...
Attempting to update "cps" command...... [OK]

command "cps" already up-to-date
Attempting to update "dns" command...
Attempting to update "dns" command...... [OK]

command "dns" already up-to-date
Attempting to update "firewall" command...
Attempting to update "firewall" command...... [OK]

command "firewall" already up-to-date
Attempting to update "gss-cli" command...
Attempting to update "gss-cli" command...... [FAIL]

Unable to fetch updates
$

**Comment by dshafik** [comment]
> This release is primarily to add logging around package installation. To use, set the ENV variable AKAMAI_LOG to one of PANIC, FATAL, ERROR, WARN, INFO, DEBUG, or TRACE (case-insensitive), with the output being cumulative from left to right (e.g. TRACE will show all logs).

Just FYI.

**Comment by dctheobald** [comment]
I'm having a similar issue while trying to debug why akamai upgrade is failing trying to move from v1.1.3 to v1.1.4 - in this case nothing is output to the console

**Comment by lkowalsk-akamai-com** [comment]
Hi, additional logging was added in 1.2.0.
