### ISSUE TITLE
An issue that could not add host to a KSD product

### ISSUE THREAD

**Issue by yuanchang-akm** [akamai/cli#76]
We got an error when add hosts to a KSD config.
I think there may be something wrong for verify the productID.
Our customer need this to be solved as soon as possible.
The error info below is from our customer, please don't use this config directly.
Thank you very much.

akamai property --config /usr/app/akamai/bin/property_security_cpcode_cred.txt --section propertyandsecurityandcpcode modify Suntory_Dynamic_Standard_verify_KSD --addhosts testnishimura.co.jp --edgehostname san3.suntory.standard.site.edgekey.net
--
 
... searching propertyName for Suntory_Dynamic_Standard_verify_KSD
... getting info for prp_397585
... retrieving list of Products for this contract
ERROR:  TypeError: Cannot read property 'productId' of undefined
at __dirname.addHostnames.edgeHostname._getProperty.then.then.product (/snapshot/khunter/.akamai-cli/src/cli-property/src/website.js:0:0)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property 'productId' of undefined
at __dirname.addHostnames.edgeHostname._getProperty.then.then.product (/snapshot/khunter/.akamai-cli/src/cli-property/src/website.js:0:0)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by synedra** [comment]
I’d need the customer’s credentials to figure this out – it’s looking for a list of products and whatever KSD is showing up as isn’t included.  I can add it, if you know the string used for that product.

Kirsten

**Comment by yuanchang-akm** [comment]
@synedra 
I can't get the customer's credential and paste it here.
And I found that this is an existing issue.
https://github.com/akamai/cli-property/issues/73
Does KSD has its own productID?

**Comment by synedra** [comment]
I've added prd_Site_Defender to the code so it should be able to navigate properly.  Without credentials I can't test, though I could try it with the account-switch flag if the customer is cool with it.

**Comment by yuanchang-akm** [comment]
@synedra 
Thank you very much.
I tested the command after updating to the latest property module.
It seems that that problem has been resolved, but I still got an error like this.
Could you please confirm it again?
You can use account-switch flag test it bellow as it's my own config.

$akamai property --config ./property_security_cpcode_cred.txt --section propertyandsecurityandcpcode modify suntory1.ksd.test.xyz --addhosts testycsuntory1.test.xyz --edgehostname suntory.ksd.test.xyz.edgesuite.net

... searching propertyName for suntory1.ksd.test.xyz
... getting info for prp_512639
... retrieving list of Products for this contract
... retrieving list of hostnames {ctr_C-F0IVM7 : grp_103375 : prp_512639}
... retrieving list of hostnames {ctr_C-F0IVM7 : grp_103375 : prp_512639}
Updating property hostnames
Adding hostname testycsuntory1.test.xyz
Adding hostname suntory1.ksd.test.xyz

ERROR: 
	 "Unable to assign hostname.  Please try to add the hostname in 30 minutes using the --addhosts flag." 

Unable to assign hostname.  Please try to add the hostname in 30 minutes using the --addhosts flag.

**Comment by yuanchang-akm** [comment]
@synedra 
This problem need to be resolved as soon as possible.
Could you please check it?

**Comment by yuanchang-akm** [comment]
@synedra 
Hi, do you have any update about this issue?

**Comment by lkowalsk-akamai-com** [comment]
Hi @yuanchang-akm, can you let us know if this is still an issue?
