### ISSUE TITLE
Can not make new config version base on a specify version

### ISSUE THREAD

**Issue by yuanchang-akm** [akamai/cli#77]
For example:
The latest version of the config is version 11
But we want to make a new version 12 based on version 8.
Even though we new --propver option to set a specify version 8.
The new version 12 will be made by copying version 11.

akamai property --config ./property_security_cpcode_cred.txt --section propertyandsecurityandcpcode modify suntory2.ksd.test.xyz --propver 8 --new

... searching propertyName for suntory2.ksd.test.xyz
... getting info for prp_512641
Creating new version for suntory2.ksd.test.xyz
... copy property (suntory2.ksd.test.xyz) v11
Command time: 0.089 mins

**Comment by yuanchang-akm** [comment]
@synedra 
This problem need to be resolved as soon as possible.
Could you please check it?

**Comment by synedra** [comment]
You need to open the issue on the cli-property repository.  I’m on PTO starting today, possibly Davey Shafik can have our contractors work on it.

Thanks,
Kirsten

**Comment by yuanchang-akm** [comment]
@synedra

Thank you for your reply.
I have opened an issue on cli-property repository.
This is an urgent issue, I appreciate it if you can follow this issue.
