### ISSUE TITLE
Global Traffic Management API

### ISSUE THREAD

**Issue by bobstrecansky** [akamai/cli#78]
Is adding a Global Traffic Management CLI tool in the pipeline?  We'd really love to be able to control our GTM domains using the API.

**Comment by dshafik** [comment]
@bobstrecansky do you mean that you want to control GTM via the _CLI_? There is an API ([here](https://developer.akamai.com/api/web_performance/global_traffic_management/v1.html)), and while we plan to build a CLI in the future it isn't in the schedule yet.

**Comment by bobstrecansky-mc** [comment]
Correct @dshafik - we would like to be able to control GTM via the CLI.  I assume the best thing for me to do at this point is to use the GTM API until GTM controls are built into the CLI.  Is there a ticket / issue I could watch in regarding controlling GTM via the CLI?  Our main use cases for controlling GTM via the CLI would be:

- changing weighted load balancing weight
- activating new GTM configurations
- monitoring liveness test object results
- validating GTM traffic flow

**Comment by bobstrecansky** [comment]
Correct @dshafik - we would like to be able to control GTM via the CLI. I assume the best thing for me to do at this point is to use the GTM API until GTM controls are built into the CLI. Is there a ticket / issue I could watch in regarding controlling GTM via the CLI? Our main use cases for controlling GTM via the CLI would be:

changing weighted load balancing weight
activating new GTM configurations
monitoring liveness test object results
validating GTM traffic flow
