### ISSUE TITLE
Authentication issue for private Repo

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli#8]
Unable to fetch private repo in github.

Here is the command line log. username and repo are starred.

./akamai get m*******r/cli-c*********n
Attempting to fetch command...... [FAIL]
Unable to clone repository: authentication required

**Comment by dshafik** [comment]
If you use the full SSH url, e.g. `git@github.com:USERNAME/REPO_NAME.git` Akamai CLI will automatically use your SSH keys to authenticate.

You can get that URL by going to the green "Clone or Download" button above the list of files on your repo page, and clicking "Use SSH":

<img width="426" alt="akamai_cli-example-php__an_example_command_for_akamai_cli_written_in_php" src="https://user-images.githubusercontent.com/58074/28434776-81faed90-6d45-11e7-85f7-ede1890a6f31.png">

HTTPS authentication is not currently supported. I am going to close this and open a new ticket to add support for that.
