### ISSUE TITLE
Make .edgerc location configurable

### ISSUE THREAD

**Issue by ChrisScottThomas** [akamai/cli#81]
We're running CI build agents in Kubernetes with Akamai CLI on them for pipelines implementation.

Due to the inability to place .edgerc in a custom location, and globally pass where that location is, creates a host of issues.  Mainly due to the fact we're passing the .edgerc file as a Kubernetes secret, it overwrites the contents of where we tell the file to be placed, breaking the CLI's functionality to install new packages as the folder becomes readonly.

We tried using the --edgerc flag, but it seemed to fail no matter how we passed it?

We tried to alias it, which never worked:
`alias akamai='akamai --edgerc /etc/akamai/.edgerc'`

```
# akamai pl list-contracts --edgerc /etc/akamai/.edgerc
Akamai Pipeline Error: 'cli_unknown_option' occurred:
 Unknown option: '--edgerc'
```

```
# akamai pl --edgerc /etc/akamai/.edgerc
Akamai Pipeline Error: 'cli_unknown_option' occurred:
 Unknown option: '--edgerc'
```

```
# akamai --edgerc /etc/akamai/.edgerc pl
Incorrect Usage. flag provided but not defined: -edgerc
```

The only way we managed to fix this, is by placing the file in a custom location as a Kubernetes secret, and then symlinking to the expected location in the Dockerfile, which is a bit ... meh.

Ideally this should be configurable in the config file:
```
[credentials]
location = /my/custom/file
```

an env var:
`AKAMAI_CREDENTIALS=/my/custom/file`

where `$AKAMAI_CREDENTIALS` is defaulted to `$HOME/.edgerc`, but at least it's customisable

or a flag that works, being passed against `akamai --edgerc /my/custom/file <command>` not `akamai <command> --edgerc /my/custom/file` which can then be passed via an alias for `akamai`, and will work every time.

**Comment by lkowalsk-akamai-com** [comment]
We believe that this issue is fixed with 1.3.0 release. Please feel free to reaopen the ticket if thats not the case.
