### ISSUE TITLE
cURL with default User-Agent fails to pull package-list.json

### ISSUE THREAD

**Issue by jfrome** [akamai/cli#82]
When I attempt to build the docker image, the build fails on the following section:
```
curl https://developer.akamai.com/cli/package-list.json | jq .packages[].name | sed s/\"//g | xargs akamai install --force
```
Manually testing the curl command, the following error occurs:
```
$ curl https://developer.akamai.com/cli/package-list.json                                                                                    
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;developer&#46;akamai&#46;com&#47;cli&#47;package&#45;list&#46;json" on this server.<P>
Reference&#32;&#35;18&#46;44db1cb8&#46;1564180069&#46;52c1fda
</BODY>
</HTML>
```

However, when I specify an empty User-Agent header, it works:
```
curl -A '' https://developer.akamai.com/cli/package-list.json                                                                                      
{                                     
    "version": 1.0,                                               
    "packages": [                    
...
```       

There appears to be some WAF/Property configuration that is blocking the request based on the User-Agent.  Updating the Dockerfile with the following results in a successful build:
```
curl -A '' https://developer.akamai.com/cli/package-list.json | jq .packages[].name | sed s/\"//g | xargs akamai install --force
```

**Comment by javiergarza** [comment]
@jfrome yes, we have Akamai's Web Application Firewall fronting resources under developer.akamai.com. Let me see if we can get the documentation updated to ensure any command line requests pass a user-agent

**Comment by javiergarza** [comment]
@jfrome I updated the dockerfile, please let me know if this solves the issue and I will close this issue. Thanks!

**Comment by javiergarza** [comment]
I got this

**Comment by javiergarza** [comment]
Closing issue

**Comment by jfrome** [comment]
@javiergarza Unfortunately, adding
```
-A 'curl'
```
still returns "Access Denied".  The following User-Agents have worked for me:
```
-A ''
```
or
```
-A 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0'
```

**Comment by javiergarza** [comment]
My bad, I should have tried it. I changed the dockerfile to use -A '' which works
