### ISSUE TITLE
support for credentials via environment variables

### ISSUE THREAD

**Issue by zerolaser** [akamai/cli#87]
I was wondering if you could allow the akamai crendentials to be picked up from environment variables. we would like our CI/CD system to pull the akamai docker image and pass in those akamai credentials as environment variables and run the required akamai commands.

**Comment by synedra** [comment]
This already exists, what command were you working on?  I can find the right CLI property env vars for you.

Kirsten

**Comment by lordscarlet** [comment]
I am attempting to use the purge command, and have had trouble finding documentation on using ENV variables

**Comment by thompsong** [comment]
+1 trying to use purge command with env vars.

**Comment by jeffabailey** [comment]
Where's the documentation on the environment variables you can use in place of the .edgerc?

**Comment by jgrumboe** [comment]
I'm also searching for the ENV variables and found this in the source code: 
https://github.com/akamai/cli/blob/784e3e786937a6e34087706c3540122407fbd862/pkg/config/config.go#L137

Also this project is referencing how to use env variables:
https://github.com/b13/akamai/blob/master/README.md#credentials

It's possible to do it like that:
AKAMAI_DEFAULT_CLIENT_SECRET = xxxxx
AKAMAI_DEFAULT_HOST = xxxxx.purge.akamaiapis.net
AKAMAI_DEFAULT_ACCESS_TOKEN = xxxxx
AKAMAI_DEFAULT_CLIENT_TOKEN = xxxxx

**Comment by robertolopezlopez** [comment]
Hi,

@zerolaser, @lordscarlet, @grahamethompson, @jeffabailey : the piece of code that @jgrumboe is pointing to SETS authentication details to environment variables.

CLI does not handle authentication by itself; instead, this is done by each submodule. We (Akamai CLI team) do not currently control any of those submodules. As you may guess, most probably they all read the `.edgerc` file. I am not so sure about the environment variables.

I hope this answer is clear enough, I will close this issue now. If you are really interested in using environment variables for authentication, you should check each submodule that you intend to use, and in case of running into trouble create an issue in their repository.

Kind regards,

Roberto
