### ISSUE TITLE
Akamai CLI not updating packages

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli#88]
The update command doesn't seem to work on the Akamai CLI. I updated the cli-image-manager and the update command doesn't seem to pick it up.
The search package seems to find the right version:

$ akamai search image-manager
Results Found: 1

Package: Image Manager [image-manager]
  Command: image-manager (alias: im)
  Version: 0.1.8
  Description: An Akamai CLI package for Image Manager

Install using "akamai install [package]".

But the install doesn't pull the new version

$ AKAMAI_LOG=trace akamai update image-manager
TRACE[0000] Python binary found: /Users/jgarza/.pyenv/shims/python2
TRACE[0000] Pip binary found: /Users/jgarza/.pyenv/shims/pip2
TRACE[0000] Command found: /Users/jgarza/.pyenv/shims/python2/Users/jgarza/.akamai-cli/src/cli-image-manager/bin/akamai-image-manager
Attempting to update "image-manager" command...
TRACE[0000] Searching for package repo
TRACE[0000] Repo found: /Users/jgarza/.akamai-cli/src/cli-image-manager
TRACE[0000] Fetching from remote: origin
TRACE[0000] Repo already up-to-date
TRACE[0000] Using ref: refs/remotes/origin/master
TRACE[0000] Resolving HEAD
TRACE[0000] HEAD is the same as the remote: a7513858a85c68e9e2a0256cb8a9cf331a3e1623 (old) vs a7513858a85c68e9e2a0256cb8a9cf331a3e1623 (new)
Attempting to update "image-manager" command...... [OK]

Here you can see the HEAD on my local repo (after running "git pull") has the right head, but the one on the local CLI has an old one:

cli-image-manager jgarza$ cat .git/refs/remotes/origin/master
d6ba8944348f8318cfd9dc8c9986bb6f1054766c

cli-image-manager jgarza$ cat /Users/jgarza/.akamai-cli/src/cli-image-manager/.git/refs/remotes/origin/master
a7513858a85c68e9e2a0256cb8a9cf331a3e1623

Seems to me the "akamai update" command is not pulling the remote head

Can somebody please take a look?

**Comment by javiergarza** [comment]
According to https://github.com/src-d/go-git/issues/545 probably we just need to update line 92 (see below) of https://github.com/akamai/cli/blob/master/command_update.go to use a pull instead of a Fetch

err = repo.Fetch(&git.FetchOptions{

**Comment by joaquin-gimenez** [comment]
@javiergarza this issue was reported before related to another package and I had a look into it and could not find a solution, I had tried using both go-git's fetch and pull with the same outcome so it leads me to think it's an issue with go-git

**Comment by IanCassTwo** [comment]
Seems there's a pull request for a fix for this issue. Any chance you can look at it, test it and merge it if it works? It's a pain not being able to update cli plugins https://github.com/akamai/cli/pull/91

**Comment by dctheobald** [comment]
This bug, at least testing with EdgeWorkers CLI update, seems to be resolved with Akamai CLI v1.1.5

**Comment by javiergarza** [comment]
Thanks for the update @dctheobald ! closing the issue
