### ISSUE TITLE
Docs for initial setup would be helpful

### ISSUE THREAD

**Issue by ismith** [akamai/cli#9]
Specifically, where do I put credentials?

**Comment by dshafik** [comment]
Thanks for reporting this issue, onboarding and developer experience are top priorities for this project.

I have added documentation [here](https://github.com/akamai/cli#credentials), let me know if that solves your issue.

**Comment by aarlaud** [comment]
How are the release supposed to be installed? That OSX image doesn't seem to be a dmg. Please share install instructions.
thanks

**Comment by ktyacke** [comment]
@aarlaud The file you downloaded is the actual executable, so there's nothing to install. You run it by executing `./akamai-0.1.1-macamd64` That should get you up and running. You may also run into a permission denied message when you first run it, if so, you'll want to chmod the file permissions to 755. Thanks for the feedback, we'll be sure to clarify this in the docs!

**Comment by dshafik** [comment]
I've added full documentation on this now that should solve any issues:

https://github.com/akamai/cli#download-a-release-binary

If you have further issues, please open a new ticket.

Thanks!
