### ISSUE TITLE
upgrade command doesn't seem to work on akamai brew binary

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli#93]
I am running "akamai" cli version 1.1.4 (installed via brew) and the "upgrade" command mentioned on the [README.md](https://github.com/akamai/cli#upgrading) documentation doesn't seem to be supported/available

$ akamai --version
akamai version 1.1.4

$ akamai upgrade
Usage:
  akamai [global flags] command [command flags] [arguments...]

Built-In Commands:
  config
  help
  install (alias: get)
  list
  search
  uninstall
  update

Installed Commands:
  property

Global Flags:
   --bash     Output bash auto-complete
   --zsh          Output zsh auto-complete
   --proxy value  Set a proxy to use

**Comment by dctheobald** [comment]
That's strange - it works for me.  I'm currently running Akamai CLI v1.1.4

**Comment by javiergarza** [comment]
Yes, it only happens when you install the CLI using brew: "brew install akamai"

**Comment by alexander-rondon** [comment]
Hello, binary assets are gone, please, could you bring them back?
it brakes the Dockerfile when you run:

```wget `curl https://api.github.com/repos/akamai/cli/releases/latest | jq .assets[].browser_download_url | grep linuxamd64 | grep -v sig | sed s/\"//g` && \
    mv akamai-*-linuxamd64 /usr/local/bin/akamai && chmod +x /usr/local/bin/akamai```

https://github.com/akamai/cli/blob/ce41543499627433d9fe5fe0330d926ee406c41f/Dockerfile#L30

**Comment by dctheobald** [comment]
Hi @alexander-rondon - sorry for the inconvenience.  We are currently working out an issue with releasing the binaries for v1.1.5 which is why that Docker URL is broken.  In the meantime, you can change your local copy of the Dockerfile to use this URL instead: https://api.github.com/repos/akamai/cli/releases/tags/1.1.4 which should pull the binaries from the last version that had binaries available.  Thanks!

**Comment by dctheobald** [comment]
CLI v1.1.5 has been released and the binaries re-added as attachments to the release.  I believe this new release solves the upgrade issue.

**Comment by alexander-rondon** [comment]
Thank you very much!

**Comment by javiergarza** [comment]
Brew works now (see below). BTW I am going to close this issue as now that I think about it it is expected the akamai binary installed with brew doesn't have the upgrade option as it is upgraded using "brew upgrade akamai" Dah!

$ brew upgrade akamai
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
akamai ✔ bind deno gradle imagemagick@6 nativefier rtags vert.x
aws-cdk bnd ghq imagemagick libtensorflow@1 pkcs11-helper sile

==> Upgrading 1 outdated package:
akamai 1.1.4 -> 1.1.5
==> Upgrading akamai
==> Downloading https://homebrew.bintray.com/bottles/akamai-1.1.5.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a9/a986f3bfc261227cd44447d5ff9cdfb461c50c002118d36caed068f5859432e1?__gda__=exp=1579933034~hmac=f9f6470530e58d6a460d33364e7aaa47884ec5bb4c10aae3a3ad1e209c26f961&response-content-disposi
######################################################################## 100.0%
==> Pouring akamai-1.1.5.catalina.bottle.tar.gz
🍺 /usr/local/Cellar/akamai/1.1.5: 5 files, 15MB
Removing: /usr/local/Cellar/akamai/1.1.4... (5 files, 15MB)
Removing: /Users/jgarza/Library/Caches/Homebrew/akamai--1.1.4.catalina.bottle.tar.gz... (7.4MB)
==> Checking for dependents of upgraded formulae...
==> No dependents found!
