### ISSUE TITLE
Execution of Akamai fails in docker

### ISSUE THREAD

**Issue by partamonov** [akamai/cli#96]
Image: alpine

Akamai CLI version: v1.1.5

After installation I am getting
```shell
/# wget -O /bin/akamai https://github.com/akamai/cli/releases/download/1.1.5/akamai-1.1.5-linuxamd64
Connecting to github.com (140.82.118.4:443)
...
saving to '/bin/akamai'
'/bin/akamai' saved

/ # chmod +x akamai
chmod: akamai: No such file or directory
/ # chmod +x /bin/akamai
/ # akamai
/bin/sh: akamai: not found
```

then if I install several packages

```shell
# apk add --no-cache --update openssl \
        ca-certificates \
        libc6-compat \
        libstdc++
...
# akamai --version
Error relocating /usr/local/bin/akamai: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/akamai: __fprintf_chk: symbol not found
```

I cannot reproduce this issue on previous releases or on for example centos7 image

**Comment by partamonov** [comment]
Also see `Error relocating /usr/local/bin/akamai` as I installed binary to `/bin`

**Comment by lukaszczerpak** [comment]
In order to have full compatibility with alpine, I suggest to build from source on Alpine linux - here are the steps:

```
❯ docker run -it --rm alpine

apk add --no-cache go git
go get -d github.com/akamai/cli
cd /root/go/src/github.com/akamai/cli
go mod init
go mod tidy
# -ldflags="-s -w" strips debug information from the executable 
go build -o /akamai -ldflags="-s -w"
```

To prevent keeping all dev dependencies in the image, the recommendation is to use multistage build - see example here: https://github.com/akamai/akamai-docker/blob/master/dockerfiles/cli.Dockerfile

**Comment by lkowalsk-akamai-com** [comment]
Hi @partamonov, we have now removed Dockerfile from this repository and as it is maintained else where. Please see Install with Docker section in README - https://github.com/akamai/cli#install-with-docker
